const EXAMPLE_APP = 'EXAMPLE_APP';

export const ExampleAppActions = {
  INIT_EXAMPLE_APP: `${EXAMPLE_APP}.INIT_EXAMPLE_APP`,

  CREATE_EXAMPLE: `${EXAMPLE_APP}.CREATE_EXAMPLE`,

  POST_EXAMPLE: `${EXAMPLE_APP}.CREATE_EXAMPLE`,
  POST_EXAMPLE_SUCCESS: `${EXAMPLE_APP}.CREATE_EXAMPLE_SUCCESS`,
  POST_EXAMPLE_FAIL: `${EXAMPLE_APP}.POST_EXAMPLE_FAIL`,

  FETCH_EXAMPLE: `${EXAMPLE_APP}.FETCH_EXAMPLE`,
  FETCH_EXAMPLE_SUCCESS: `${EXAMPLE_APP}.FETCH_EXAMPLE_SUCCESS`,
  FETCH_EXAMPLE_FAIL: `${EXAMPLE_APP}.FETCH_EXAMPLE_FAIL`,
  SET_FETCH_EXAMPLE_DATA: `${EXAMPLE_APP}.SET_FETCH_EXAMPLE_DATA`,

  UPDATE_EXAMPLE: `${EXAMPLE_APP}.UPDATE_EXAMPLE`,
  UPDATE_EXAMPLE_SUCCESS: `${EXAMPLE_APP}.UPDATE_EXAMPLE_SUCCESS`,
  UPDATE_EXAMPLE_FAIL: `${EXAMPLE_APP}.UPDATE_EXAMPLE_FAIL`,

  DELETE_EXAMPLE: `${EXAMPLE_APP}.DELETE_EXAMPLE`,
  DELETE_EXAMPLE_SUCCESS: `${EXAMPLE_APP}.DELETE_EXAMPLE_SUCCESS`,
  DELETE_EXAMPLE_FAIL: `${EXAMPLE_APP}.DELETE_EXAMPLE_FAIL`,
};
