const EXAMPLE_APP = 'EXAMPLE_APP';

export const ExampleAppActions = {
  FETCH_EXAMPLE: `${EXAMPLE_APP}.FETCH_EXAMPLE`,
  FETCH_EXAMPLE_SUCCESS: `${EXAMPLE_APP}.FETCH_EXAMPLE_SUCCESS`,
  FETCH_EXAMPLE_FAIL: `${EXAMPLE_APP}.FETCH_EXAMPLE_FAIL`,
  SET_FETCH_EXAMPLE_DATA: `${EXAMPLE_APP}.SET_FETCH_EXAMPLE_DATA`,
  SET_FETCH_EXAMPLE_IS_LOADING: `${EXAMPLE_APP}.SET_FETCH_EXAMPLE_IS_LOADING`,
};
